# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43db51f1a7f30ed096a76d361c1d6db44101c8c0ef8a1b9330304d18d308ebb64ff8ceeb891cc87b3b7c3235078ed2aac82576a0791929d4996dff78e0cedddd

test:
  secret_key_base: 7c5fc1b4125f0e63a41d13a139228cb1e6ef2552a64743d5710ccb515894d0bc28319efc796197272b688536959c94e09103840586811bbfb40fef9693c987f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
